services:
  url_shortener_postgres_test:
    image: postgres:alpine
    container_name: url_shortener_postgres_test
    restart: no
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  url_shortener_redis_test:
    image: redis:alpine
    container_name: url_shortener_redis_test
    restart: no
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6381:6379'
    volumes:
      - redis_data:/data

networks:
  default:
    name: url_shortener_test

volumes:
  postgres_data:
  redis_data:
