services:
  url_shortener_postgres_dev:
    image: postgres:alpine
    container_name: url_shortener_postgres_dev
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5433:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  url_shortener_redis_dev:
    image: redis:alpine
    container_name: url_shortener_redis_dev
    restart: always
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6380:6379'
    volumes:
      - redis_data:/data

networks:
  default:
    name: url_shortener_dev

volumes:
  postgres_data:
  redis_data:
