services:
  url_shortener_app:
    image: ${DOCKERHUB_USERNAME}/url-shortener:latest
    container_name: url_shortener_app
    restart: always
    env_file:
      - .env.production
    ports:
      - "127.0.0.1:${PORT}:${PORT}"
    depends_on:
      - url_shortener_postgres
      - url_shortener_redis

  url_shortener_postgres:
    image: postgres:alpine
    container_name: url_shortener_postgres
    restart: always
    env_file:
      - .env.production
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  url_shortener_redis:
    image: redis:alpine
    container_name: url_shortener_redis
    command: redis-server --requirepass ${REDIS_PASSWORD}
    restart: always
    volumes:
      - redis_data:/data

networks:
  default:
    name: url_shortener

volumes:
  postgres_data:
  redis_data:
