services:
  nest_starter_postgres_test: # Edit
    image: postgres:alpine
    container_name: nest_starter_postgres_test # Edit
    restart: no
    env_file:
      - .env.test
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    ports:
      - '5434:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
  
  nest_starter_redis_test: # Edit
    image: redis:alpine
    container_name: nest_starter_redis_test # Edit
    restart: no
    command: redis-server --requirepass ${REDIS_PASSWORD}
    ports:
      - '6381:6379'
    volumes:
      - redis_data:/data

networks:
  default:
    name: nest_starter_test # Edit

volumes:
  postgres_data:
  redis_data:
