name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*']

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test
  e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Create .env.test
        run: |
          cat <<EOF > .env.test
          NODE_ENV=test
          POSTGRES_USER=username
          POSTGRES_PASSWORD=password
          DATABASE_URL="postgresql://username:password@localhost:5434/mydb?schema=public" 
          REDIS_PASSWORD=password
          REDIS_URL="redis://:password@localhost:6381"
          ADMIN_SECRET=superultrahypersecret
          PORT=3001
          HOST=http://localhost:3001
          EOF
      - name: Run e2e tests
        run: pnpm test:e2e
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          # REDIS_PASSWORD: password
