name: Tests
on:
  push:
    branches:
      - main
  pull_request:
    branches: ['*']

jobs:
  unit-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Run tests
        run: pnpm test
  int-e2e-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/build
      - name: Generate .env.test for CI
        run: |
          echo "POSTGRES_USER=$POSTGRES_USER" > .env.test
          echo "POSTGRES_PASSWORD=$POSTGRES_PASSWORD" > .env.test
          echo "REDIS_PASSWORD=$REDIS_PASSWORD" > .env.test
      - name: Run integration and e2e tests
        run: pnpm test:e2e:ci
        env:
          POSTGRES_USER: username
          POSTGRES_PASSWORD: password
          REDIS_PASSWORD: password
          NODE_ENV: test
          HOST: http://localhost:3001
          PORT: 3001
          DATABASE_URL: postgresql://username:password@localhost:5434/mydb?schema=public
          ADMIN_SECRET: superultrahypersecret
          REDIS_URL: redis://:password@localhost:6381
